name: CI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Setup .Net Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Install Dependencies
        run: dotnet restore
      - name: Build
        working-directory: ./smartsheet-csharp-sdk-docs
        run: dotnet build --configuration Release --no-restore
      - uses: nikeee/docfx-action@v1.0.0
        working-directory: ./smartsheet-csharp-sdk-docs
        name: Build Documentation
        with:
          args: docfx.json