name: CI

on:
  push:
    branches: [ mainline ]
  pull_request:
    branches: [ mainline ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Setup .Net Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Install Dependencies
        run: |
          dotnet restore
#          dotnet tool install coveralls.net --version 4.0.1 --tool-path tools
#          dotnet add mock-api-test-sdk-net60 package altcover --version 8.5.841
      - name: Build
        working-directory: ./smartsheet-csharp-sdk
        run: dotnet build --configuration Release --no-restore
      - name: Clone smartsheet/smartsheet-sdk-tests PRIVATE repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'smartsheet'
          repository: 'smartsheet-sdk-tests'
          access-token: ${{ secrets.SDK_TEST_ACCESS_TOKEN }}
      - name: Setup Mock API
        run: |
          smartsheet-sdk-tests/travis_scripts/install_wiremock.sh
          smartsheet-sdk-tests/travis_scripts/start_wiremock.sh
      - name: Run Mock API Tests
        working-directory: ./mock-api-test-sdk-net60
        run: |
          dotnet build --configuration Release --no-restore
          dotnet test --no-restore /p:CollectCoverage=true /p:CoverletOutput=$GITHUB_WORKSPACE/coverage.opencover.xml /p:CoverletOutputFormat=opencover
          ls
          cd $GITHUB_WORKSPACE
          ls
      - name: Install coveralls.net
        run: |
          dotnet tool install coveralls.net --version 4.0.1 --tool-path tools
      # - name: Coveralls Finished
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     path-to-lcov: $GITHUB_WORKSPACE/coverage.opencover.xml
      - name: Upload to Coveralls
        run: |
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          ./tools/csmacnz.Coveralls --opencover -i $GITHUB_WORKSPACE/coverage.opencover.xml --repoToken ${{ secrets.COVERALLS_REPO_TOKEN }} --commitId ${GITHUB_SHA} --commitBranch $GIT_BRANCH --commitAuthor "${GITHUB_ACTOR}" --commitMessage "${{ github.event.head_commit.message }}" --jobId ${GITHUB_JOB}  --serviceName github-actions  --useRelativePaths
