name: CI

on:
  push:
    branches: [ mainline ]
  pull_request:
    branches: [ mainline ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - name: Setup .Net Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'
      - name: Install Dependencies
        run: dotnet restore
      - name: Build
        working-directory: ./
        run: dotnet build --configuration Release --no-restore
      - name: Checkout smartsheet-sdk-tests
        uses: actions/checkout@v6
        with:
          repository: smartsheet/smartsheet-sdk-tests
          path: smartsheet-sdk-tests
      - name: Setup Mock API
        run: |
          docker compose -f smartsheet-sdk-tests/docker-compose.yml up -d --wait
      - name: Run Mock API Tests
        working-directory: ./mock-api-test-sdk-net80
        run: |
         dotnet test --no-restore
